# Site settings
title: Tableau Web Data Connector
email: jdominguez@tableau.com
description: Connect to your web data from Tableau.
baseurl: "/"
permalinks: pretty

# Build settings
markdown: kramdown
highlighter: rouge
