# Site settings
title: Tableau Web Data Connector
email: jdominguez@tableau.com
description: Connect to your web data from Tableau.
baseurl: "/webdataconnector"
permalinks: pretty

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude
exclude: ['node_modules']
